# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_email_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
